#!/bin/bash

function pkgmngr_from () {
    dpkg -S ${FILE}|cut -d: -f1 |head -1
}

function pkgmngr_show () {
    apt show ${PKG}
}

function pkgmngr_search () {
    apt search ${SEARCH}
}

function pkgmngr_displaywebsite () {
    if [ ${DEBUG} == "yes" ]; then
	echo "Website"
    fi
    apt show ${PKG} |grep Homepage
}

function pkgmngr_compile () {
    PKGMNGR_BUILD=`which apt-build`

    if [ ${DEBUG} == "yes" ]; then
	which apt-build
	echo "Apt-build = $APTBUILD"
    fi


    if [ -n $PKGMNGR_BUILD ]; then
	sudo apt-get install apt-build
	dpkg-reconfigure apt-build
    fi
    
    echo "Build ${PKG}"
    sudo apt-build install ${PKG}
}

function pkgmngr_install () {
    if [ ${DEBUG} == "yes" ]; then
	echo "Install"
    fi
    sudo apt-get install ${PKG}
}


function pkgmngr_download () {
    if [ ${DEBUG} == "yes" ]; then
	echo "Install"
    fi
    sudo apt-get -d install ${PKG}
}

