#!/bin/bash
###########################################################
#
# Template
#
#
#
###########################################################

# Libraries
# source ${HOME}/bin/libs/ask

###########################################################
#
# function help
#
#
#
###########################################################
function help () {
cat<<EOF
Usage:
EOF
}

function list_kernels () {
    RUNNING_VERSION=$(uname -r | cut -f1 -d"-")
    RUNNING_PATCH=$(uname -r | cut -f2 -d"-")
    dpkg -l linux-* | awk '/^ii/{ print $2}' | grep -v -e $(uname -r | cut -f1,2 -d"-") | grep -e [0-9] | grep -E "(image|headers)"

}

function remove_kernels () {
    dpkg -l linux-* | awk '/^ii/{ print $2}' | grep -v -e $(uname -r | cut -f1,2 -d"-") | grep -e [0-9] | grep -E "(image|headers)" | xargs sudo apt-get -y purge
    }



###########################################################
#
# function main
#
#
#
###########################################################
function main () {

    while [ -n "$1" ] 
    do
	case $1 in
	    --debug) DEBUG="yes"; shift 1;;
	    *) help; exit;;
	esac
    done

    list_kernels

}

main "$@"
