#!/bin/bash

#---------------------------------------------------------------------
## @param type
## @param message
##
## Enters a debug message if the type of debug message != 'no'
##
## The 'type' is usually the name of the file the debug statement
## comes from. i.e. DEBUG_liblock, DEBUG_libsorcery, DEBUG_cast etc.
##
#---------------------------------------------------------------------
function debug()  {
    DEBUG="$1"
    FUNCTION="$2"
    MSG="$3"

    if [[ -n $DEBUG ]]; then
	echo "In function:-  $FUNCTION $MSG"
    fi
}
