#!/bin/bash

source ${HOME}/bin/libs/colors

LOWUSE=50
MEDUSE=75
HIGHUSE=90
ALERTUSE=95

#LOWTEMP=
#MEDTEMP=
#HIGHTEMP=
#ALERTTEMP=

function loadave () {
    echo $(cat /proc/loadavg | awk '{print $1}')
}

function loadper () {
    local LOAD=$(loadave)
    local CORES=$(grep 'model name' /proc/cpuinfo | wc -l)
    local LOADPER=$(echo ${LOAD} ${CORES} | awk '{print $1 / $2 * 100}' | cut -d. -f1)
    echo -ne "${LOADPER}"
}

function loadcolor () {
    local LOADCOLOR=""
    local LOADPER=$(loadper)
    if [ ${LOADPER} -gt ${HIGHUSE} ]; then 
	LOADCOLOR="${ALERT}"
    elif [ ${LOADPER} -gt ${MEDUSE} ]; then 
	LOADCOLOR="${RED}"
    elif [ ${LOADPER} -gt ${LOWUSE} ]; then 
	LOADCOLOR="${BRED}"
    else 
	LOADCOLOR="${BLUE}"
    fi
    echo -ne "$LOADCOLOR"
}

function loadinfo () {
    local LOAD=$(loadave)
    local LOADPER=$(loadper)
    local LC=$(loadcolor)
    echo -ne "${LC} ${LOAD} ${LOADPER}"
}

function distroinfo () {
    [ -r /etc/lsb-release ] && . /etc/lsb-release

    if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
        # Fall back to using the very slow lsb_release utility
        local DISTRIB_DESCRIPTION=$(lsb_release -s -d)
    fi
    echo -ne "${DISTRIB_DESCRIPTION}"
}

function osinfo () {
    local KERNEL=$(uname -r)
    local OPERATING_SYSTEM=$(uname -o)
    echo -ne "${KERNEL} ${OPERATING_SYSTEM}"
}

function uptimeinfo () {
    local UPTIMEHOURS=$(uptime |cut -d, -f-2|cut -d\  -f4-)
#    local UPTIMEDAYS=$
#    local UPTIME=$(awk '{print int($1/86400)" day(s) "int($1%86400/3600)":"int(($1%3600)/60)":$(
    echo -ne "${UPTIMEHOURS}"
}

function uprecordinfo () {
    local UPRECORDS=$(uprecords| grep -e "   1"|cut -d\| -f1|cut -d\  -f9-|head -n 1)
    echo -ne "${UPRECORDS}"
}

function meminfo () {
    if [ -z ${BOXNAME} ]; then
	local SI="--si"
    fi
    MEMORY=$(free -gh ${SI} | head -n 2 | tail -n 1 | awk {'print $2'})
    MEMUSED=$(free -gh ${SI} | head -n 2 | tail -n 1 | awk {'print $3'})
    MEMFREE=$(free -gh ${SI} | head -n 2 | tail -n 1 | awk {'print $4'})
    MEMPER=$(free -m | awk '/Mem/ { printf("%3.1f", $3/$2*100) }')
    MEMPER2=$(echo ${MEMPER} | cut -d. -f1)

    if [ ${MEMPER2} -lt ${MEDUSE} ]; then
        MC=${GREEN}
    elif [ ${MEMPER2} -ge ${MEDUSE} ] && [ ${MEMPER2} -lt ${HIGHUSE} ]; then
        MC=${YELLOW}
    else MC=${RED}
    fi

    echo -ne "${MC}${MEMORY} ${MEMUSED}/${MEMFREE} ${MEMPER}"
}

function swapinfo() {
if [ -z ${BOXNAME} ]; then
local SI="--si"
fi
    SWAP=$(free -gh ${SI} | tail -n 1 |awk {'print  $2'})
    SWAPUSED=$(free -gh ${SI} | tail -n 1 | awk {'print $3'})
    SWAPFREE=$(free -gh ${SI} | tail -n 1 | awk {'print $4'})
    SWAPPER=$(free -m | awk '/Swap/ { printf("%3.1f", $3/$2*100) }')
    SWAPPER2=$(echo ${SWAPPER} | cut -d. -f1)

    if [ ${SWAPPER2} -lt ${MEDUSE} ]; then
        SC=${GREEN}
    elif [ ${SWAPPER2} -ge ${MEDUSE} ] && [ ${SWAPPER2} -lt ${HIGHUSE} ]; then
        SC=${YELLOW}
    else SC=${RED}
    fi

    echo -ne "${SC}${SWAP} ${SWAPUSED}/${SWAPFREE} ${SWAPPER}"
}

function diskinfo() {
    DISK=$(df -h / | awk '{ a = $2 } END { print a }')
    DISKUSED=$(df -h / | awk '{ a = $3 } END { print a }')
    DISKFREE=$(df -h / | awk '{ a = $4 } END { print a }')
    DISKPER=$(df -h / | awk '/\// {print $(NF-1)}')
#    DISKPER=$(awk '{printf("%3.1f", $1/$2*100) $DISKUSED $DISK }')
    DISKPER2=$(echo ${DISKPER} | cut -d% -f1)


    if [ ${DISKPER2} -lt ${MEDUSE} ]; then
        HC=${GREEN}
    elif [ ${DISKPER2} -ge ${MEDUSE} ] && [ ${DISKPER2} -lt ${HIGHUSE} ]; then
        HC=${YELLOW}
    else HC=${RED}
    fi

    echo -ne "${HC}${DISK} ${DISKUSED}/${DISKFREE} ${DISKPER}"
}

function lastlogininfo () {
    local USERNAME=$(whoami)
    LASTDAY=$(lastlog -u ${USERNAME} | tail -n 1| awk '{ printf("%s", $4) }')
    LASTDATE=$(lastlog -u ${USERNAME} | tail -n 1| awk '{ printf("%s", $6) }')
    LASTMONTH=$(lastlog -u ${USERNAME} | tail -n 1| awk '{ printf("%s", $5) }')
    LASTTIME=$(lastlog -u ${USERNAME} | tail -n 1| awk '{ printf("%s", $7) }')
    LASTYEAR=$(lastlog -u ${USERNAME} | tail -n 1| awk '{ printf("%s", $9) }')
    LASTFROM=$(lastlog -u ${USERNAME} | tail -n 1| awk '{ printf("%s", $3) }')
    LASTLOG="${LASTDAY} ${LASTYEAR} ${LASTMONTH} ${LASTDATE} ${LASTTIME} ${LASTFROM}"
    echo -ne "$LASTLOG"
}

function usersinfo () {
    LOGGEDINUSERS=$(w -hs | cut -d " " -f1 | sort | uniq)
    echo -ne "$LOGGEDINUSERS"
}



function cpuinfo () {
    local CPU=$(cat /proc/cpuinfo | grep 'model name' | head -1 | cut -d':' -f2)
    echo -ne "${CPU}"
}

function ipinfo () {
    local IPADDR=$(ip route get 1 | awk '{print $NF;exit}')
    echo -ne "$IPADDR"
}

function ispinfo () {
    local EXTIPADDR=$(myip)
    local ISP=$(geoiplookup ${EXTIPADDR} |grep ASN |cut -d: -f2)
    echo -ne "$ISP"
}

function location_zip() {
    local EXTIPADDR=$(myip)
    local ZIP=$(geoiplookup ${EXTIPADDR}|grep City| awk '{ printf "%s", $10 }'|cut -d, -f1)
    echo -ne "${ZIP}"
}

function locationinfo () {
    local EXTIPADDR=$(myip)
    local ZIP=$(location_zip)
    local CITY=$(geoiplookup ${EXTIPADDR}|grep City| awk '{ printf "%s", $9 }'|cut -d, -f1)
    local STATE=$(geoiplookup ${EXTIPADDR}|grep City| awk '{ printf "%s", $8 }'|cut -d, -f1)

    echo -ne "${CITY} ${STATE} ${ZIP}"

}

function disktempinfo () {
    local SDATEMP=$(/usr/sbin/hddtemp -uf /dev/sda|cut -c 36-)
    local SDBTEMP=$(/usr/sbin/hddtemp -uf /dev/sdb|cut -c 36-)

    echo -ne "$SDATEMP $SDBTEMP"
}

function cputempinfo () {
    local CPUTEMPC=$(sensors | grep "Core 0" | cut -d: -f2 | cut -d\( -f1)
    local CPUTEMP=$(sensors -f | grep "Core 0" | cut -d: -f2 | cut -d\( -f1)
    echo -ne "${CPUTEMP} ${CPUTEMPC}"
}
