#!/bin/bash

#########################################
# function search
#
# determines if flac files exist in current directory
#
# if flac files exist, calls convert_flac
# else gets directory info and continues on down to the next level
#
#########################################
function search () {
    for FILE in *
    do
	if [ -d "$FILE" ]; then
	    if cd "$FILE"; then
		DIRECTORY="${DIRECTORY}/${FILE}"
		DEEP=`expr $DEEP + 1`
		search
	    fi
	else
	    search_file
	fi
    done
    cd ..
    if [ "$DEEP" -ne "0" ]; then # if DEPTH is greater than 0, reduce depth
	DIRECTORY="`echo ${DIRECTORY} | cut -d\/ -f -$DEEP`"
    else
	SWFI=1              # ==> set flag showing that search is done.
    fi
    DEEP=`expr $DEEP - 1`  # ==> Decrement depth.    
}
