#!/bin/bash

function weathertempinfo () {
    ZIP=$(location_zip)
    TEMP=$(weather ${ZIP} | grep Temp| awk '{ printf("%s", $2)}')
    DEGF='°F'
    TEMPC=$(weather ${ZIP} | grep Temp | awk '{ printf("%s", $4)}')
    DEGC='°C'
    TEMPCOLOR=$(weather ${ZIP}|grep Temp|cut -d: -f2|cut -c 2-3)


    SUPFREEZE="${BCYAN}"
    FREEZE="${BBLUE}"
    COLD="${BLUE}"
    CHILI="${BGREEN}"
    MILD="${GREEN}"
    NORMAL="${YELLOW}"
    WARM="${BYELLOW}"
    HOT="${BRED}"
    VHOT="${RED}"
    DANGER="${ALERT}"

    # Colour progression is important ... 
    # bold gray -> bold green -> bold yellow -> bold red -> 
    # black on red -> bold white on red 
    # 
    # Then we have to choose the values at which the colours switch, with 
    # anything past yellow being pretty important. 

    if [ ${TEMPCOLOR} -lt 0 ]; then 
	TC=$SUPFREEZE
    elif [ ${TEMPCOLOR} -ge 0 ] && [ ${TEMPCOLOR} -lt 33 ]; then 
        TC=${FREEZE}
    elif [ ${TEMPCOLOR} -ge 33 ] && [ ${TEMPCOLOR} -lt 50 ]; then 
	TC=${COLD}
    elif [ ${TEMPCOLOR} -ge 50 ] && [ ${TEMPCOLOR} -lt 60 ]; then 
	TC=${CHILI}
    elif [ ${TEMPCOLOR} -ge 60 ] && [ ${TEMPCOLOR} -lt 67 ]; then                     TC=${MILD}
    elif [ ${TEMPCOLOR} -ge 67 ] && [ ${TEMPCOLOR} -lt 76 ]; then 
	TC=${NORMAL}
    elif [ ${TEMPCOLOR} -ge 76 ] && [ ${TEMPCOLOR} -lt 85 ]; then
	TC=${WARM}
    elif [ ${TEMPCOLOR} -ge 85 ] && [ ${TEMPCOLOR} -lt 92 ]; then
        TC=${HOT}
    elif [ ${TEMPCOLOR} -ge 92 ] && [ ${TEMPCOLOR} -lt 100 ]; then
	TC=${VHOT}
    else TC=${ALERT}
    fi
 
    echo -ne "${TC}${TEMP}${DEGF} ${TEMPC}${DEGC} ${DC}"
}


function weatherskyinfo () {
    ZIP=$(location_zip)
    SKY=$(weather ${ZIP}|grep Sky|cut -d: -f2)

    SUPFREEZE="${BCYAN}"
    FREEZE="${BBLUE}"
    COLD="${BLUE}"
    CHILI="${BGREEN}"
    MILD="${GREEN}"
    NORMAL="${YELLOW}"
    WARM="${BYELLOW}"
    HOT="${BRED}"
    VHOT="${RED}"
    DANGER="${ALERT}"

    # Colour progression is important ... 
    # bold gray -> bold green -> bold yellow -> bold red -> 
    # black on red -> bold white on red 
    # 
    # Then we have to choose the values at which the colours switch, with 
    # anything past yellow being pretty important. 

    if [ "${SKY}" == "clear" ]; then 
	TC=${SUPFREEZE}
    elif [ "${SKY}" == "cloudy" ]; then 
        TC=${FREEZE}
    elif [ "${SKY}" == "mostly cloudy" ]; then 
	TC=${COLD}
#    elif [ "${SKY}" == "" ]; then 
#	TC=${CHILI}
#    elif [ ${TEMPCOLOR} -ge 60 ] && [ ${TEMPCOLOR} -lt 67 ]; then
#	TC=${MILD}
#    elif [ ${TEMPCOLOR} -ge 67 ] && [ ${TEMPCOLOR} -lt 76 ]; then 
#	TC=${NORMAL}
#    elif [ ${TEMPCOLOR} -ge 76 ] && [ ${TEMPCOLOR} -lt 85 ]; then
#	TC=${WARM}
#    elif [ ${TEMPCOLOR} -ge 85 ] && [ ${TEMPCOLOR} -lt 92 ]; then
#        TC=${HOT}
#    elif [ ${TEMPCOLOR} -ge 92 ] && [ ${TEMPCOLOR} -lt 100 ]; then
#	TC=${VHOT}
    else TC=${ALERT}
    fi
 
    echo -ne "${TC} ${SKY} ${DC}"
}

function weatherhumidityinfo () {
    local ZIP=$(location_zip)
    HUMIDITY=$(weather ${ZIP}|grep Rel| awk '{ printf "%s", $3 }' | cut -c-2)

    SUPFREEZE="${BCYAN}"
    FREEZE="${BBLUE}"
    COLD="${BLUE}"
    CHILI="${BGREEN}"
    MILD="${GREEN}"
    NORMAL="${YELLOW}"
    WARM="${BYELLOW}"
    HOT="${BRED}"
    VHOT="${RED}"
    DANGER="${ALERT}"

    # Colour progression is important ... 
    # bold gray -> bold green -> bold yellow -> bold red -> 
    # black on red -> bold white on red 
    # 
    # Then we have to choose the values at which the colours switch, with 
    # anything past yellow being pretty important. 

#    if [ ${HUMIDITY} -lt 0 ]; then 
#	TC=$SUPFREEZE
#    elif [ ${HUMIDITY} -ge 0 ] && [ ${HUMIDITY} -lt 33 ]; then 
#        TC=${FREEZE}
#    elif [ ${HUMIDITY} -ge 33 ] && [ ${HUMIDITY} -lt 50 ]; then 
#	TC=${COLD}
#    elif [ ${HUMIDITY} -ge 50 ] && [ ${HUMIDITY} -lt 60 ]; then 
#	TC=${CHILI}
#    elif [ ${HUMIDITY} -ge 60 ] && [ ${HUMIDITY} -lt 67 ]; then
#    TC=${MILD}
#    elif [ ${HUMIDITY} -ge 67 ] && [ ${HUMIDITY} -lt 76 ]; then 
#	TC=${NORMAL}
#    elif [ ${HUMIDITY} -ge 76 ] && [ ${HUMIDITY} -lt 85 ]; then
#	TC=${WARM}
#    elif [ ${HUMIDITY} -ge 85 ] && [ ${HUMIDITY} -lt 92 ]; then
#        TC=${HOT}
#    elif [ ${HUMIDITY} -ge 92 ] && [ ${HUMIDITY} -lt 100 ]; then
#	TC=${VHOT}
#    else TC=${ALERT}
#    fi
 
    echo -ne "${HUMIDITY}%"
}

function weatherwindinfo () {
# Weather wind formats
#
# 1. "from the NW (310 degrees) at 6 MPH (5 KT)"
# 2. "Variable at 6 MPH (5 KT)
# 3. "Calm"
#
#
#
    local ZIP=$(location_zip)
    local WIND=$(weather ${ZIP}|grep Wind|cut -d: -f2)
    local WINDFORMAT=$(echo $WIND | awk '{ printf "%s", $2 }')
    if [[ "${WINDFORMAT}" == "from" ]]; then
	local WINDSPEED=$(echo $WIND | awk '{ printf "%s", $7 }')
	WINDSPEED="${WINDSPEED} MPH"
	local WINDTYPE=$(echo $WIND | awk '{ printf "%s %s", $1 $2 }')
	local WINDDIR=$(echo $WIND | awk '{ printf "%s", $3 }')
	local WINDDEG=$(echo $WIND | awk '{ printf "%s %s", $4 $5}')
	local WINDSPEEDKT=$(echo $WIND | awk '{ printf "%s %s", $9 $10 }')
    elif [[ "${WINDFORMAT}" == "Variable" ]]; then
	local WINDSPEED=$(echo $WIND | awk '{ printf "%s", $4 }')
	WINDSPEED="${WINDSPEED} MPH"
	local WINDTYPE=$(echo $WIND | awk '{ printf "%s", $2 }')
	local WINDSPEEDKT=$(echo $WIND | awk '{ printf "%s %s", $6 $7}')
    else
	local WINDSPEED=$(echo $WIND | awk '{ printf "%s", $3 }')
	local WINDTYPE=$(echo $WIND | awk '{ printf "%s", $1 }')
	local WINDSPEEDKT=$(echo $WIND | awk '{ printf "%s", $5 }')
    fi
    SUPFREEZE="${BCYAN}"
    FREEZE="${BBLUE}"
    COLD="${BLUE}"
    CHILI="${BGREEN}"
    MILD="${GREEN}"
    NORMAL="${YELLOW}"
    WARM="${BYELLOW}"
    HOT="${BRED}"
    VHOT="${RED}"
    DANGER="${ALERT}"

    # Colour progression is important ... 
    # bold gray -> bold green -> bold yellow -> bold red -> 
    # black on red -> bold white on red 
    # 
    # Then we have to choose the values at which the colours switch, with 
    # anything past yellow being pretty important. 

#    if [ ${WINDSPEED} -lt 0 ]; then 
#	TC=$SUPFREEZE
#   elif [ ${WINDSPEED} -ge 0 ] && [ ${WINDSPEED} -lt 33 ]; then 
#        TC=${FREEZE}
#    elif [ ${WINDSPEED} -ge 33 ] && [ ${WINDSPEED} -lt 50 ]; then 
#	TC=${COLD}
#    elif [ ${WINDSPEED} -ge 50 ] && [ ${WINDSPEED} -lt 60 ]; then 
#	TC=${CHILI}
#    elif [ ${WINDSPEED} -ge 60 ] && [ ${WINDSPEED} -lt 67 ]; then
#          TC=${MILD}
#    elif [ ${WINDSPEED} -ge 67 ] && [ ${WINDSPEED} -lt 76 ]; then 
#	TC=${NORMAL}
#    elif [ ${WINDSPEED} -ge 76 ] && [ ${WINDSPEED} -lt 85 ]; then
#	TC=${WARM}
#    elif [ ${WINDSPEED} -ge 85 ] && [ ${WINDSPEED} -lt 92 ]; then
#        TC=${HOT}
#    elif [ ${WINDSPEED} -ge 92 ] && [ ${WINDSPEED} -lt 100 ]; then
#	TC=${VHOT}
#    else TC=${ALERT}
#    fi
 
    echo -ne "${WINDTYPE} ${WINDDIR} ${WINDDEG} at ${WINDSPEED} ${WINDSPEEDKT}"
}
